# Generated by Django 5.2.8 on 2025-12-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='Дата рождения пользователя', null=True),
        ),
    ]
