# Generated by Django 5.2.8 on 2025-12-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_source',
            field=models.CharField(choices=[('local', 'Локальная'), ('google', 'Google'), ('facebook', 'Facebook')], default='local', max_length=50, verbose_name='Источник регистрации'),
        ),
    ]
