# Generated by Django 5.2.8 on 2025-12-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_confirmationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
